version: "3.9"
   
services:
  # postgres:
  #   image: postgres:14.0-alpine
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   healthcheck:
  #       test: ["CMD-SHELL", "pg_isready -U postgres"]
  #       interval: 5s
  #       timeout: 5s
  #       retries: 5
  api:
    ports:
      - 8080:80
    build: ./backend
    volumes:
      - ./backend:/backend
    # environment:
    #   - DB_NAME=postgres
    #   - DB_USER=postgres
    #   - DB_PASSWORD=postgres
    #   - DB_HOST=postgres
    #   - DB_PORT=5432
    # restart: on-failure:5
    # depends_on:
    #   postgres:
    #     condition: service_healthy