version: "3.9"
   
volumes:
  node_modules:
services:
  api:
    build:
      context: .
      target: api
    ports:
      - 8080:80
    volumes:
      - ./backend/.:/app
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 80 --reload  --reload-dir /app"]
  web:
    build:
      context: .
      target: webbase
    ports:
      - 3000:5173
    volumes:
      - ./frontend/.:/app
      - node_modules:/app/node_modules/
    command: ["sh", "-c", "npm run dev"]