name: Test and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_TAG: followben/groundsim:test
  LATEST_TAG: followben/groundsim:latest

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    name: Test
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and export to Docker
      uses: docker/build-push-action@v3
      with:
        context: .
        load: true
        tags: ${{ env.TEST_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Test
      run: |
        docker run --rm ${{ env.TEST_TAG }}

  publish:
    if: github.ref_name == 'main'
    needs: test
    environment: dev
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: followben/groundsim
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: production
          push: true
          tags: ${{ env.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max