name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
    - uses: actions/checkout@v3
    - run: docker build --target test -t test-api . && docker run test-api

  publish:
    if: github.ref_name == 'main'
    needs: test
    environment: dev
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action
        with:
          images: followben/groundsim
      
      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}