name: Test and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_TAG: test
  LATEST_TAG: latest
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:

  test-api:
    runs-on: ubuntu-latest
    environment: dev
    name: Test api
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and export to Docker
      uses: docker/build-push-action@v3
      with:
        context: .
        target: apitest
        load: true
        tags: followben/gsapi:${{ env.TEST_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Test
      run: |
        docker run --rm followben/gsapi:${{ env.TEST_TAG }}

  publish-api:
    if: github.ref_name == 'main'
    needs: test-api
    environment: dev
    name: Publish api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: followben/gsapi
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: api
          push: true
          tags: followben/gsapi:${{ env.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-api:
      needs: publish-api
      environment: dev
      name: Deploy api
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --config fly.api.toml --remote-only

  publish-web:
    if: github.ref_name == 'main'
    needs: test-api
    environment: dev
    name: Publish web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: followben/gs
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: web
          push: true
          tags: followben/gs:${{ env.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-web:
      needs: publish-web
      environment: dev
      name: Deploy web
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --config fly.web.toml --remote-only